[package]
name = "scoped-css-macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "2", features = ["full"] }
sha2 = "0.10"

proc-macro2 = "1"
